// <auto-generated />
using System;
using DueDiligenceChecker.Shared.Infrastructure.Persistence.EFC.Configuration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DueDiligenceChecker.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DueDiligenceChecker.IAM.Domain.Model.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("fullname");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("password_hash");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("UserId")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", "iam");
                });

            modelBuilder.Entity("DueDiligenceChecker.Suppliers.Domain.Model.Entities.History.InterpolScreeningHit", b =>
                {
                    b.Property<int>("InterpolScreeningHitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("interpol_screening_hit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterpolScreeningHitId"));

                    b.Property<string>("Charges")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("charges");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("family_name");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("forename");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gender");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nationality");

                    b.Property<string>("PlaceOfBirth")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("place_of_birth");

                    b.Property<int>("SupplierScreeningId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_screening_id");

                    b.HasKey("InterpolScreeningHitId")
                        .HasName("pk_interpol_screening_hits");

                    b.HasIndex("SupplierScreeningId")
                        .HasDatabaseName("ix_interpol_screening_hits_supplier_screening_id");

                    b.ToTable("interpol_screening_hits", "suppliers");
                });

            modelBuilder.Entity("DueDiligenceChecker.Suppliers.Domain.Model.Entities.History.SecopScreeningHit", b =>
                {
                    b.Property<int>("SecopScreeningHitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("secop_screening_hit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SecopScreeningHitId"));

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contract_number");

                    b.Property<string>("ContractorDocument")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contractor_document");

                    b.Property<string>("ContractorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contractor_name");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("entity_name");

                    b.Property<string>("EntityTaxId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("entity_tax_id");

                    b.Property<DateTime?>("FinalizedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("finalized_at");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("level");

                    b.Property<DateTime?>("LoadedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("loaded_at");

                    b.Property<string>("Municipality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("municipality");

                    b.Property<string>("Order")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("order");

                    b.Property<string>("ProcessUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("process_url");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("published_at");

                    b.Property<string>("ResolutionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolution_number");

                    b.Property<decimal?>("SanctionAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sanction_amount");

                    b.Property<int>("SupplierScreeningId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_screening_id");

                    b.HasKey("SecopScreeningHitId")
                        .HasName("pk_secop_screening_hits");

                    b.HasIndex("SupplierScreeningId")
                        .HasDatabaseName("ix_secop_screening_hits_supplier_screening_id");

                    b.ToTable("secop_screening_hits", "suppliers");
                });

            modelBuilder.Entity("DueDiligenceChecker.Suppliers.Domain.Model.Entities.History.SmvScreeningHit", b =>
                {
                    b.Property<int>("SmvScreeningHitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("smv_screening_hit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SmvScreeningHitId"));

                    b.Property<string>("Amount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("amount");

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("date");

                    b.Property<string>("Resolution")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolution");

                    b.Property<string>("ResolutiveResolutionDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolutive_resolution_date");

                    b.Property<string>("ResolutiveResolutionNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolutive_resolution_number");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("summary");

                    b.Property<int>("SupplierScreeningId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_screening_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<string>("WithAppeal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("with_appeal");

                    b.HasKey("SmvScreeningHitId")
                        .HasName("pk_smv_screening_hits");

                    b.HasIndex("SupplierScreeningId")
                        .HasDatabaseName("ix_smv_screening_hits_supplier_screening_id");

                    b.ToTable("smv_screening_hits", "suppliers");
                });

            modelBuilder.Entity("DueDiligenceChecker.Suppliers.Domain.Model.Entities.History.SupplierScreening", b =>
                {
                    b.Property<int>("SupplierScreeningId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supplier_screening_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierScreeningId"));

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("executed_at");

                    b.Property<bool>("HasHits")
                        .HasColumnType("bit")
                        .HasColumnName("has_hits");

                    b.Property<string>("SourcesChecked")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sources_checked");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.HasKey("SupplierScreeningId")
                        .HasName("pk_supplier_screenings");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_supplier_screenings_supplier_id");

                    b.ToTable("supplier_screenings", "suppliers");
                });

            modelBuilder.Entity("DueDiligenceChecker.Suppliers.Domain.Model.Entities.Representative", b =>
                {
                    b.Property<int>("RepresentativeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("representative_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RepresentativeId"));

                    b.Property<int?>("Age")
                        .HasColumnType("int")
                        .HasColumnName("age");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("Nationality")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nationality");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<int>("SupplierId")
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    b.HasKey("RepresentativeId")
                        .HasName("pk_representatives");

                    b.HasIndex("SupplierId")
                        .HasDatabaseName("ix_representatives_supplier_id");

                    b.ToTable("representatives", "suppliers");
                });

            modelBuilder.Entity("DueDiligenceChecker.Suppliers.Domain.Model.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("supplier_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierId"));

                    b.Property<string>("CorporateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("corporate_name");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone_number");

                    b.Property<string>("PhysicalAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("physical_address");

                    b.Property<string>("TradeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trade_name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebSite")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("web_site");

                    b.HasKey("SupplierId")
                        .HasName("pk_suppliers");

                    b.ToTable("suppliers", "suppliers");
                });

            modelBuilder.Entity("DueDiligenceChecker.Suppliers.Domain.Model.Entities.History.InterpolScreeningHit", b =>
                {
                    b.HasOne("DueDiligenceChecker.Suppliers.Domain.Model.Entities.History.SupplierScreening", null)
                        .WithMany("InterpolHits")
                        .HasForeignKey("SupplierScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_interpol_screening_hits_supplier_screenings_supplier_screening_id");
                });

            modelBuilder.Entity("DueDiligenceChecker.Suppliers.Domain.Model.Entities.History.SecopScreeningHit", b =>
                {
                    b.HasOne("DueDiligenceChecker.Suppliers.Domain.Model.Entities.History.SupplierScreening", null)
                        .WithMany("SecopHits")
                        .HasForeignKey("SupplierScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_secop_screening_hits_supplier_screenings_supplier_screening_id");
                });

            modelBuilder.Entity("DueDiligenceChecker.Suppliers.Domain.Model.Entities.History.SmvScreeningHit", b =>
                {
                    b.HasOne("DueDiligenceChecker.Suppliers.Domain.Model.Entities.History.SupplierScreening", null)
                        .WithMany("SmvHits")
                        .HasForeignKey("SupplierScreeningId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_smv_screening_hits_supplier_screenings_supplier_screening_id");
                });

            modelBuilder.Entity("DueDiligenceChecker.Suppliers.Domain.Model.Entities.History.SupplierScreening", b =>
                {
                    b.HasOne("DueDiligenceChecker.Suppliers.Domain.Model.Entities.Supplier", null)
                        .WithMany()
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_supplier_screenings_suppliers_supplier_id");
                });

            modelBuilder.Entity("DueDiligenceChecker.Suppliers.Domain.Model.Entities.Representative", b =>
                {
                    b.HasOne("DueDiligenceChecker.Suppliers.Domain.Model.Entities.Supplier", null)
                        .WithMany("Representatives")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_representatives_suppliers_supplier_id");
                });

            modelBuilder.Entity("DueDiligenceChecker.Suppliers.Domain.Model.Entities.Supplier", b =>
                {
                    b.OwnsOne("DueDiligenceChecker.Suppliers.Domain.Model.ValueObjects.AnnualBilling", "Billing", b1 =>
                        {
                            b1.Property<int>("SupplierId")
                                .HasColumnType("int")
                                .HasColumnName("supplier_id");

                            b1.Property<decimal>("Amount")
                                .HasPrecision(18, 2)
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("annual_billing_amount");

                            b1.HasKey("SupplierId");

                            b1.ToTable("suppliers", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId")
                                .HasConstraintName("fk_suppliers_suppliers_supplier_id");
                        });

                    b.OwnsOne("DueDiligenceChecker.Suppliers.Domain.Model.ValueObjects.TaxIdentification", "TaxId", b1 =>
                        {
                            b1.Property<int>("SupplierId")
                                .HasColumnType("int")
                                .HasColumnName("supplier_id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)")
                                .HasColumnName("tax_identification");

                            b1.HasKey("SupplierId");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("ix_suppliers_tax_identification");

                            b1.ToTable("suppliers", "suppliers");

                            b1.WithOwner()
                                .HasForeignKey("SupplierId")
                                .HasConstraintName("fk_suppliers_suppliers_supplier_id");
                        });

                    b.Navigation("Billing")
                        .IsRequired();

                    b.Navigation("TaxId")
                        .IsRequired();
                });

            modelBuilder.Entity("DueDiligenceChecker.Suppliers.Domain.Model.Entities.History.SupplierScreening", b =>
                {
                    b.Navigation("InterpolHits");

                    b.Navigation("SecopHits");

                    b.Navigation("SmvHits");
                });

            modelBuilder.Entity("DueDiligenceChecker.Suppliers.Domain.Model.Entities.Supplier", b =>
                {
                    b.Navigation("Representatives");
                });
#pragma warning restore 612, 618
        }
    }
}
